version: "3.9"
services:
  ui:
    build:
      context: ui
      network: host
    env_file:
      - .env
    ports:
      - "80:80"

  backend:
    build:
      context: backend
      network: host
    env_file:
      - .env
    ports:
      - "8080:80"
